### ISSUE TITLE
week5 - experiment 4, not able to see HTML and javacript source code

### ISSUE THREAD

**Issue by appuCoding** [isha112/webdev#5]
week5 - experiment 4, not able to see HTML source code

**Comment by isha112** [comment]
Hi Sneha. I checked my code for the file preview and it seems okay to me. I don't know why it is not displaying it. Can you please hep me out? Here is my code snippet:

<pre>
&lt;a href="../../fileview/Default.aspx?~/experiments/week5/ng-routing/routing.html" class="btn btn-primary" target="_blank"&gt;View HTML Source&lt;/a&gt;
&lt;a href="../../fileview/Default.aspx?~/experiments/week5/js/routing.js" class="btn btn-primary" target="_blank"&gt;View javascript&lt;/a&gt;</pre>
